block:
  start: EMERALD_BLOCK
  end: REDSTONE_BLOCK
  return: LAPIS_BLOCK
  teleport: BEACON
map:
  reward:
    finish: 10
    kill: 5
messages:
  start:
    title: ''
    sub: §a出生点设置在 (§2%x%§a,§2%y%§a,§2%z%§a)
  finish:
    title: §6§l恭喜
    sub: ''
  kill:
    title: ''
    sub: §6你杀死了%player%
  damaged1:
    title: ''
    sub: §c你受到了§4 %n%§c 点伤害
  damaged2:
    title: ''
    sub: §c致命伤害！
  speed:
    title: ''
    sub: §b%n% 方块/秒
  dead1: "%player% §f掉入虚空"
  dead2: "%player% §f被 %killer% §f推下了虚空"
  villager: "§6靶子"
blockskin:
  '0': SANDSTONE
  '5': WOOL:8
  '10': WOOL:1
  '20': WOOL:6
  '50': WOOL:9
  '100': WOOL:1
  '200': WOOL:14
  '500': WOOL:2
  '1000': DIAMOND_BLOCK